### ISSUE TITLE
UTF Grid Interactivity

### ISSUE THREAD

**Issue by tstan** [SLUGIS/firehistory#1]

**Comment by oeon** [comment]
(interactivity) doesn't seem to work for me on iOS

**Comment by tstan** [comment]
@oeon Mapbox has a separate SDK for iOS interactivity <a href> https://www.mapbox.com/mapbox-ios-sdk/#api_overview</a> but I will still look into workarounds; I can think of a couple ways it might work still next week.

**Comment by oeon** [comment]
there's also https://www.mapbox.com/mapbox.js/example/v1.0.0/multilayer-utfgrid/ in the old example, i think we used jquery to add/remove layers/grids when they were toggled

**Comment by tstan** [comment]
Confirmed fixed through 6f081b0 work around

**Comment by oeon** [comment]
omg love it. Wasn't a fan of the hover anyway. Great work!
