### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by oeon** [SLUGIS/firehistory#3]
can we make it responsive? like with Bootstrap or similar http://getbootstrap.com/?

**Comment by tstan** [comment]
How about using the built in mapbox.js Leaflet and instead making each layer just a tick box like this?

<a href="http://imgur.com/sRO4EUg"><img src="http://i.imgur.com/sRO4EUg.jpg" title="source: imgur.com" /></a>

**Comment by oeon** [comment]
looks great, nice idea! :+1:
